make file server

diff --git a/TP1-ARM/src/Makefile b/TP1-ARM/src/Makefile
--- a/TP1-ARM/src/Makefile
+++ b/TP1-ARM/src/Makefile
@@ -5,7 +5,19 @@ sim: shell.c sim.c instructions/sim_instructions.c utils.c
 clean:
 	rm -rf *.o *~ sim
 
+run_server: sim
+	run_c: sim
+	@if [ -z "$(file)" ]; then echo "Error: Debes proporcionar un valor para 'file'. Usa: make run file=nombre"; exit 1; fi
+	echo -e "go\nrdump\nquit" | ./sim ../inputs/bytecodes/$(file).x
+	echo -e "go\nrdump\nquit" | ../ref_sim_x86 ../inputs/bytecodes/$(file).x
+	make clean
 
+run_server_n: sim
+	@if [ -z "$(file)" ]; then echo "Error: Debes proporcionar un valor para 'file'. Usa: make run file=nombre"; exit 1; fi
+	@if [ -z "$(n)" ]; then echo "Error: Debes proporcionar un valor para 'n'. Usa: make run file=nombre n=valor"; exit 1; fi
+	echo -e "run $(n)\nrdump\nquit" | ./sim ../inputs/bytecodes/$(file).x
+	echo -e "run $(n)\nrdump\nquit" | ../ref_sim_x86 ../inputs/bytecodes/$(file).x
+	make clean
 run_k: sim
 	@if [ -z "$(file)" ]; then echo "Error: Debes proporcionar un valor para 'file'. Usa: make run file=nombre"; exit 1; fi
 	echo -e "go\nrdump\nquit" | ./sim ../inputs/bytecodes/$(file).x
@@ -15,7 +27,7 @@ run_k: sim
 run_c: sim
 	@if [ -z "$(file)" ]; then echo "Error: Debes proporcionar un valor para 'file'. Usa: make run file=nombre"; exit 1; fi
 	echo -e "go\nrdump\nquit" | ./sim ../inputs/bytecodes/$(file).x
-	echo -e "go\nrdump\nquit" | ../sim_ref_x86 ../inputs/bytecodes/$(file).x
+	echo -e "go\nrdump\nquit" | ../ref_sim_x86 ../inputs/bytecodes/$(file).x
 	make clean
 
 run_k_n: sim
